# Generated by Django 5.2.4 on 2025-08-07 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('جديدة', 'جديدة'), ('قيد المعالجة', 'قيد المعالجة'), ('مجدولة', 'مجدولة'), ('أرشفت', 'أرشفت')], default='جديدة', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
